basePath: /gestrym-storage
info:
  contact: {}
  description: API para el manejo de entrenamientos.
  title: Gestrym API Storage
  version: "1.0"
paths:
  /files:
    get:
      description: Retorna los archivos asociados a una entidad específica con URLs
        pre-firmadas
      parameters:
      - description: Entity ID
        in: query
        name: entityId
        required: true
        type: string
      - description: Entity Type
        in: query
        name: entityType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Obtener archivos por entidad
      tags:
      - Storage
  /files/{id}:
    delete:
      description: Elimina un archivo del storage y de la base de datos
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Eliminar archivo
      tags:
      - Storage
  /files/upload:
    post:
      consumes:
      - multipart/form-data
      description: Sube archivos de forma concurrente, valida tipo y tamaño
      parameters:
      - description: Collection/Bucket internal path
        in: formData
        name: collection
        required: true
        type: string
      - description: Entity ID to relate (e.g., exercise ID)
        in: formData
        name: entityId
        required: true
        type: string
      - description: Entity Type to relate (e.g., 'exercise')
        in: formData
        name: entityType
        required: true
        type: string
      - description: Archivos a subir
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Subir uno o varios archivos
      tags:
      - Storage
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Key
    type: apiKey
  BasicAuth:
    type: basic
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
